= GCP Artifact Registry Maven Resource
Deploys and retrieve artifacts from a link:https://cloud.google.com/artifact-registry/docs/java[GCP Artifact Registry Maven Repository Manager].

This simple resource is build on top of the excellent link:https://github.com/nulldriver/maven-resource[Maven Resource].

== Source configuration
url:: __Required__ The location of the repository.
snapshot_url:: __Optional__ The location of the snapshot repository.
artifact:: __Required__ The artifact coordinates in the form of `groupId:artifactId:type[:classifier]`
disable_redeploy:: __Optional__ If set to `true`, will not re-deploy a release if the artifact version has been previously deployed. NOTE: has no effect for -SNAPSHOT versions or `snapshot_url`.
GOOGLE_APPLICATION_CREDENTIALS:: The credentials to connect to the repository via link:https://github.com/GoogleCloudPlatform/artifact-registry-maven-tools[artifactregistry-maven-wagon].
maven_opts:: Additional parameters for `mvn deploy:file` e.g. `-Dfiles=…`

== Behavior

=== `check`: Check for new versions of the artifact
Checks for new versions of the artifact by retrieving the `maven-metadata.xml` from
the repository.

=== `in`: Fetch an artifact from a repository.
Download the artifact from the repository.

=== `out`: Deploy artifact to a repository.
Deploy the artifact to the Maven Repository Manager.

==== Parameters
file:: __Required__ The path to the artifact to deploy.
pom_file:: __Recommended__ The path to the pom.xml to deploy with the artifact.
version_file:: __Recommended__ The path to the version file.
maven_opts:: Additional parameters for `mvn deploy:file` e.g. `-Dfiles=…`

Either the `pom_file` or the `version_file` or both files have to be declared.
When no `version_file` is provided the version from the pom is used.

== Examples
Resource configuration for an authenticated repository using a custom cert:

[source,yaml]
----
resource_types:
- name: gcp-artifact-registry-maven-resource
  type: registry-image
  source:
    repository: nemoinho/gcp-artifact-registry-maven-resource
    tag: 1

resources:
- name: artifact
  type: gcp-artifact-registry-maven-resource
  source:
    url: artifactregistry://europe-west4-maven.pkg.dev/example-project/example-repository
    artifact: com.example:example-webapp:jar
    GOOGLE_APPLICATION_CREDENTIALS: ((gcp_credentials_json))
----

Build and deploy an artifact to a Maven Repository Manager:

[source,yaml]
----
jobs:
- name: build
  plan:
  - get: source-code
    trigger: true
  - task: build-artifact
    file: source-code/ci/build.yml
  - put: artifact
    params:
      file: task-output/example-webapp-*.jar
      pom_file: source-code/pom.xml
----

Retrieve an artifact and push to Cloud Foundry using link:https://github.com/concourse/cf-resource[cf-resource].

[source,yaml]
----
jobs:
- name: deploy
  plan:
  - get: source-code
  - get: artifact
    trigger: true
  - put: cf
    params:
      manifest: source-code/manifest.yml
      path: artifact/example-webapp-*.jar
----
